<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <!-- /.box-header -->
      <div class="box-body">
        <form class="form-horizontal" method="post">
          <?php echo $form->renderAllDecorated(true) ?>

          <?php if ($phones): ?>
            <?php foreach ($phones as $phone): ?>
            <div class="form-group form-phone-plus">
              <label class="control-label col-sm-3"></label>
              <div class="col-sm-9">
                <input type="text" id="phone" name="phones[]" class="mask-phone form-control" value="<?php echo $phone ?>">
                <span class="help-block error"></span>
              </div>
            </div>
            <?php endforeach ?>
          <?php endif ?>

          <div class="form-group" id="group-add-phone">
            <div class="col-xs-12 col-sm-2 col-sm-push-10">
              <button type="button" class="btn btn-success btn-flat btn-block" id="add-phone"><i class="fa fa-plus"></i></button>
            </div>
          </div>

          <button type="submit" class="btn btn-flat btn-success pull-right">Salvar</button>
          <a href="/contacts" type="submit" class="btn btn-flat btn-danger pull-right" style="margin-right:10px">Cancelar</a>
        </form>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>