<div class="row">
  <div class="cols-xs-12">
  <div class="box">
    <div class="box-body table-responsive">
      <dl class="dl-horizontal" style="margin-top: 30px"> 
        <dt style="margin-bottom: 20px">Nome</dt> <dd><h3 style="margin:0;padding: 0"><?php echo $contact->getName() ?></h3></dd>
        <?php 
        $count = 1;
        foreach ($contact->getPhones() as $phone): ?>
          <?php if ($count == 1): ?>
            <dt>Telefones</dt>
          <?php endif ?>
          <dd><?php echo $phone->getNumber() ?></dd>
        <?php 
        $count++;
        endforeach ?>
        <dd>
          <a class="btn btn-flat btn-primary pull-right" href="/contacts">Voltar</a>
        </dd>
      </dl>
    </div>
  </div>
</div>