<!DOCTYPE HTML>
<html xmlns='http://www.w3.org/1999/xhtml' lang='pt-br'>
  <head>
    <meta http-equiv='Content-Type' content='text/html; charset=UTF-8' /> 
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv='imagetoolbar' content='no' /> 
    <meta name='resource-types' content='document' /> 
    <meta http-equiv='pragma' content='no-cache' /> 
    <meta name='revisit-after' content='1' /> 
    <meta name='robots' content='ALL' /> 
    <meta name='distribution' content='Global' /> 
    <meta name='rating' content='General' />
    <meta name='doc-class' content='Completed' /> 
    <meta name='doc-rights' content='Public' />		
    <title>Agenda</title>
    <link rel='stylesheet' type='text/css' href='/plugins/bootstrap/bootstrap.css' />
  </head>
  <body class='contrast-dark-orange error application-error sign-in contrast-background'>
    <div id='wrapper'>
      <div class='error-type'>
        <i class='icon-question-sign'></i>
        <span><?php echo $code; ?></span>
      </div>
      <div class='error-message'>
        <?php if ($code == 500): ?>
          Ooops. Algo inesperado aconteceu :( <br>
        <?php endif; ?>
        <?php echo $message; ?>
      </div>
      <div class='form-wrapper'>
        <?php echo $this->getContent(); ?>
      </div>
    </div>
  </body>
</html>