
<!-- Main content -->
<section class="content">

  <div class="error-page">
    <h2 class="headline text-red"><?php echo $code ?></h2>

    <div class="error-content">
      <br/>
      <h3 style="margin-top:30px"><i class="fa fa-warning text-red"></i> Oops! Algo deu errado.</h3>

      <p>
        <?php echo $message ?>
      </p>
      <center>
        <a class="btn btn-md btn-ablock" href="javascript:history.go(-1)">
          <i class="icon-chevron-left"></i> Voltar
        </a>
      </center>
    </div>
  </div>
  <!-- /.error-page -->

</section>
<!-- /.content -->


