<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Agenda</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Preencha seus dados para entrar</p>
    <?php
      $this->flashSession->output();
    ?>
    <form  method="post" action="/auth/register">
      <?php echo $form->renderAllDecorated() ?>
      <div class="text-center">
        <div class="g-recaptcha" data-sitekey="6LepnSMUAAAAAIeN0WLRIhWi3EwhsmXxHUL_UZZg"></div>
      </div>
      <br/>
      <div class="row">
        <div class="col-xs-4">
          <a href="/auth" class="btn btn-danger btn-block btn-flat">Cancelar</a>
        </div>
        <div class="col-xs-4 col-md-push-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Cadastrar</button>
        </div>
      </div>
    </form>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
